import { Link } from "react-router-dom";
import { Card, CardTitle, Divider, Muted, Page, Pill, Stack } from "../components/ui";

const SECTIONS = [
  {
    title: "1. Use of the Service",
    paragraphs: [
      "AuraCue provides AI-powered playlist recommendations. You agree to use the service only for lawful purposes and in accordance with these terms.",
      "You may not attempt to reverse engineer the platform, use automated systems to scrape or extract data, abuse the playlist generation system, or misuse Spotify integration.",
    ],
  },
  {
    title: "2. User Accounts",
    paragraphs: [
      "To use certain features, you may create an account.",
      "You are responsible for maintaining the confidentiality of your account and for all activity that occurs under it.",
      "AuraCue may suspend or terminate accounts that violate these terms.",
    ],
  },
  {
    title: "3. Spotify Integration",
    paragraphs: [
      "AuraCue integrates with Spotify through the Spotify Web API.",
      "By connecting Spotify, you authorize AuraCue to verify songs using Spotify and create playlists in your Spotify account.",
      "Spotify accounts remain subject to Spotify's Terms of Service. AuraCue is not affiliated with Spotify.",
    ],
  },
  {
    title: "4. AI-Generated Recommendations",
    paragraphs: [
      "Playlist recommendations are generated by artificial intelligence systems.",
      "AuraCue does not guarantee that all recommended songs exist, all tracks are available on Spotify, or recommendations will match your preferences.",
    ],
  },
  {
    title: "5. Intellectual Property",
    paragraphs: [
      "The AuraCue platform, design, branding, and software are the property of AuraCue.",
      "Music content belongs to the respective artists, labels, and Spotify. AuraCue only provides recommendations and links.",
    ],
  },
  {
    title: "6. Service Availability",
    paragraphs: [
      "AuraCue is provided “as is” and we do not guarantee uninterrupted access.",
      "We may update, modify, or discontinue features at any time.",
    ],
  },
  {
    title: "7. Limitation of Liability",
    paragraphs: [
      "AuraCue is not responsible for Spotify outages or API failures, third-party service disruptions, or errors in AI recommendations.",
    ],
  },
  {
    title: "8. Termination",
    paragraphs: [
      "We reserve the right to suspend or terminate accounts that violate these terms.",
      "Users may delete their accounts at any time.",
    ],
  },
  {
    title: "9. Changes to the Terms",
    paragraphs: [
      "We may modify these terms periodically. Continued use of the service indicates acceptance of the updated terms.",
    ],
  },
  {
    title: "10. Contact",
    paragraphs: ["For questions regarding these Terms: support@auracue.app"],
  },
] as const;

export function TermsPage() {
  return (
    <Page>
      <Card
        style={{
          background:
            "linear-gradient(135deg, color-mix(in srgb, var(--panel-strong) 90%, rgba(236, 111, 69, 0.06)) 0%, color-mix(in srgb, var(--panel-strong) 90%, rgba(37, 87, 214, 0.06)) 100%)",
        }}
      >
        <Pill style={{ width: "fit-content", marginBottom: 14 }}>Legal</Pill>
        <CardTitle style={{ fontSize: "clamp(24px, 4vw, 34px)" }}>Terms of Service</CardTitle>
        <Muted style={{ marginTop: 10 }}>Last Updated: March 2026</Muted>
        <Muted style={{ lineHeight: 1.7 }}>
          These Terms of Service govern the use of the AuraCue application. By accessing or using AuraCue, you agree
          to these terms.
        </Muted>
        <Divider />
        <Stack style={{ gap: 18 }}>
          {SECTIONS.map((section) => (
            <section key={section.title}>
              <CardTitle style={{ fontSize: 20 }}>{section.title}</CardTitle>
              <Stack style={{ gap: 10, marginTop: 10 }}>
                {section.paragraphs.map((paragraph) => (
                  <Muted key={paragraph} style={{ marginTop: 0, lineHeight: 1.75 }}>
                    {paragraph}
                  </Muted>
                ))}
              </Stack>
            </section>
          ))}
        </Stack>
        <Divider />
        <Muted style={{ marginTop: 0 }}>
          Looking for privacy details? <Link to="/privacy">Read the Privacy Policy</Link>
        </Muted>
      </Card>
    </Page>
  );
}
